//! Golden-PDF regression tests (M6, P1).
//!
//! Strategy — two layers:
//!   1. **Determinism**: rendering the same input twice MUST produce
//!      byte-identical output (SHA-256). M3 verified this property for
//!      CJK docs; this test locks it in for the whole corpus.
//!   2. **Page-count baseline**: page counts are stable across machines
//!      (fonts embed differently per platform, so byte-level hashes are
//!      NOT portable — page structure is). Baseline stored in
//!      `tests/golden/baseline.json`; regenerate with
//!      `UPDATE_GOLDEN=1 cargo test --test golden_test`.
//!
//! Corpus covers the feature surface most likely to regress silently:
//! CJK (searchable text layer), GBK rare chars, math, tables, code
//! highlighting, mixed long-form content.

use std::path::PathBuf;

/// (name, markdown) — fixed corpus, ordered.
fn corpus() -> Vec<(&'static str, &'static str)> {
    vec![
        (
            "cjk-searchable",
            r#"# CJK 可搜索性

简体中文段落：数据可视化是现代分析的关键能力。

## 繁体

這是繁體中文段落。

## 生僻字

龘靐齉爩 䶮䶰 㒭㙓 鱻麤龗
"#,
        ),
        (
            "math",
            r#"# Math

Inline: $E = mc^2$ and $a^2 + b^2 = c^2$.

Display:

$$\int_0^\infty e^{-x^2} dx = \frac{\sqrt{\pi}}{2}$$

Fraction: $\frac{1}{2} + \frac{1}{3} = \frac{5}{6}$
"#,
        ),
        (
            "table",
            r#"# Table

| 项目 | 数量 | 金额 |
|------|-----:|-----:|
| 苹果 |    3 | ¥15.00 |
| 香蕉 |    5 | ¥22.50 |
| 总计 |    8 | ¥37.50 |
"#,
        ),
        (
            "code-highlight",
            r#"# Code

```rust
fn main() {
    let x: Vec<u32> = (0..10).collect();
    println!("sum = {}", x.iter().sum::<u32>());
}
```

```python
def fib(n: int) -> int:
    return n if n < 2 else fib(n - 1) + fib(n - 2)
```
"#,
        ),
        (
            "mixed-longform",
            r#"# 长文档混合

## 第一节

这是混合内容：TypePress 引擎、**加粗**、`行内代码`、[链接](https://example.com)。

> 引用块：工业级 PDF 生成需要确定性输出。

## 第二节

1. 有序列表项
2. 第二项
3. 第三项

- 无序项 A
- 无序项 B

---

## 第三节（数学+代码）

$$f(x) = \begin{cases} x^2 & x > 0 \\ 0 & \text{otherwise} \end{cases}$$

| 键 | 值 |
|---|---|
| version | 0.4.0 |
| engine | fulgur |
"#,
        ),
    ]
}

fn golden_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/golden")
}

fn baseline_path() -> PathBuf {
    golden_dir().join("baseline.json")
}

/// Render markdown via the library API (no CLI, no font flags — same as CI).
/// Returns the PDF bytes.
fn render(md: &str) -> Vec<u8> {
    let dir = tempfile::tempdir().expect("temp dir");
    let out = dir.path().join("out.pdf");
    typepress::render_markdown_to_pdf(md, &out, &[], &[], None, None)
        .unwrap_or_else(|e| panic!("render failed: {e}"));
    std::fs::read(&out).expect("read rendered pdf")
}

fn sha256(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let mut h = Sha256::new();
    h.update(bytes);
    format!("{:x}", h.finalize())
}

#[test]
fn golden_determinism() {
    // Same input twice → byte-identical output. This is the core
    // industrial-grade property: reproducible builds.
    for (name, md) in corpus() {
        let pdf1 = render(md);
        let pdf2 = render(md);
        assert!(!pdf1.is_empty(), "{name}: empty PDF");
        assert_eq!(
            sha256(&pdf1),
            sha256(&pdf2),
            "{name}: non-deterministic output (two renders differ)"
        );
        // Sanity: real PDF header + at least one page.
        assert!(pdf1.starts_with(b"%PDF"), "{name}: not a PDF");
        assert!(crate_page_count(&pdf1) >= 1, "{name}: no pages");
    }
}

#[test]
fn golden_page_count_baseline() {
    // Page counts must match the committed baseline (stable across
    // platforms even though font embedding differs).
    if !baseline_path().exists() {
        if std::env::var("UPDATE_GOLDEN").is_ok() {
            eprintln!("SKIP: baseline regenerated by sibling test (UPDATE_GOLDEN=1)");
            return;
        }
        panic!("baseline.json missing — run UPDATE_GOLDEN=1 cargo test --test golden_test");
    }
    let baseline: std::collections::BTreeMap<String, usize> =
        serde_json::from_str(&std::fs::read_to_string(baseline_path()).expect("baseline.json"))
            .expect("parse baseline");
    assert_eq!(
        baseline.len(),
        corpus().len(),
        "baseline.json out of sync — run UPDATE_GOLDEN=1"
    );
    for (name, md) in corpus() {
        let pdf = render(md);
        let pages = crate_page_count(&pdf);
        let expected = baseline
            .get(name)
            .unwrap_or_else(|| panic!("{name}: missing from baseline"));
        assert_eq!(
            &pages, expected,
            "{name}: page count changed ({pages} != {expected}) — intentional layout change? run UPDATE_GOLDEN=1"
        );
    }
}

/// Count pages by counting /Type /Page objects (regex over raw bytes).
fn crate_page_count(pdf: &[u8]) -> usize {
    let text = String::from_utf8_lossy(pdf);
    let re = regex::Regex::new(r"/Type\s*/Page[^s]").unwrap();
    re.find_iter(&text).count()
}

/// Regenerate baseline.json from the current renderer output.
/// Driven by UPDATE_GOLDEN=1 so CI never rewrites files.
#[test]
fn golden_regenerate_when_flagged() {
    if std::env::var("UPDATE_GOLDEN").is_ok() {
        let mut map = std::collections::BTreeMap::new();
        for (name, md) in corpus() {
            let pdf = render(md);
            map.insert(name.to_string(), crate_page_count(&pdf));
        }
        let json = serde_json::to_string_pretty(&map).unwrap();
        std::fs::create_dir_all(golden_dir()).expect("create golden dir");
        std::fs::write(baseline_path(), json).expect("write baseline.json");
        eprintln!(
            "golden baseline regenerated -> {}",
            baseline_path().display()
        );
    }
}
